In [1]:
import numpy as np


In [11]:
populasyon = np.random.randint(0, 80, 10000)

In [15]:
populasyon[0:10]

array([19, 61, 37, 46,  9, 24, 41, 28, 10,  5])

In [28]:
# orneklem cekimi

np.random.seed(115)
orneklem = np.random.choice(a = populasyon, size = 100)  
orneklem[0:10]

array([13, 45, 28,  7, 21, 63, 66, 74, 79, 45])

In [29]:
orneklem.mean()

40.54

In [32]:
populasyon.mean()

39.8157

In [31]:
np.random.seed(115)
orneklem = np.random.choice(a = populasyon, size = 100)  
orneklem[0:10]

array([13, 45, 28,  7, 21, 63, 66, 74, 79, 45])

In [34]:
# orneklem dağılımı

orneklem1 = np.random.choice(a = populasyon, size = 100)
orneklem2 = np.random.choice(a = populasyon, size = 100)
orneklem3 = np.random.choice(a = populasyon, size = 100)
orneklem4 = np.random.choice(a = populasyon, size = 100)
orneklem5 = np.random.choice(a = populasyon, size = 100)
orneklem6 = np.random.choice(a = populasyon, size = 100)
orneklem7 = np.random.choice(a = populasyon, size = 100)
orneklem8 = np.random.choice(a = populasyon, size = 100)
orneklem9 = np.random.choice(a = populasyon, size = 100)
orneklem10 = np.random.choice(a = populasyon, size = 100)

(orneklem1.mean()+orneklem2.mean()+orneklem3.mean()+orneklem4.mean()+orneklem5.mean()+orneklem6.mean()+orneklem7.mean()+orneklem8.mean()+orneklem9.mean()+orneklem10.mean())/10


38.971

In [35]:
orneklem1.mean()

35.37

In [36]:
orneklem2.mean()

42.01

# Betimsel İstatistikler

In [41]:
import seaborn as sns
tips = sns.load_dataset("tips")
df = tips.copy()
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [42]:
df.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [43]:
df.describe().T

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [46]:
!pip install researchpy
import researchpy as rp